/**
 * Совместимость: реэкспорт из model.js
 */
export {
  DAYS,
  DAY_SHORT,
  DESC_MAX,
  LAST_SLOT_END,
  normalizeDay,
  jsDayToIndex,
  dayNameFromDate,
  capitalize,
  toDateKey,
  parseDateKey,
  startOfWeek,
  addDays,
  emptyStore,
  emptyDay,
  ensureDay,
  getDayItems,
  getDaySlots,
  finalizeSlots,
  isSlotActive,
  groupDayBySlots,
  parseTaskCode,
  serializeToCode,
  resolveDayItems,
  itemIsDone,
  setItemStatus,
  applyCode,
  migrateFromV1,
  isV2,
} from "./model.js";
